### ISSUE TITLE
TypeError: client.s.dbCache is not iterable

### ISSUE THREAD

**Issue by crobinson42** [seppevs/migrate-mongo#104]
**Describe the bug**
 
When I call `await db.close()` at the end of my `up(db) {...}` function this error is thrown in the console:

```
/Users/coryrobinson/.nvm/versions/node/v10.13.0/lib/node_modules/migrate-mongo/node_modules/mongodb/lib/operations/close.js:19
      for (const item of client.s.dbCache) {
                                  ^

TypeError: client.s.dbCache is not iterable
    at completeClose (/Users/coryrobinson/.nvm/versions/node/v10.13.0/lib/node_modules/migrate-mongo/node_modules/mongodb/lib/operations/close.js:19:35)
    at client.topology.close.err (/Users/coryrobinson/.nvm/versions/node/v10.13.0/lib/node_modules/migrate-mongo/node_modules/mongodb/lib/operations/close.js:35:9)
``` 

**Additional context**

i'm using a fresh install of the pkg `npm i -g migrate-mongo`, node 10.15.x, npm 6.9.x

**Comment by jole78** [comment]
also getting this

**Comment by seppevs** [comment]
You shouldn't call `db.close()` in your migration scripts. Migrate-mongo closes the connection for you.

**Comment by TeNNoX** [comment]
I also encountered this when using the migrate-mongo API

```javascript
const { db, client } = await MigrateMongo.database.connect();
try {
  const migrations = await MigrateMongo.status(db);
  // ...
} finally {
  db.close();
}
```

I think I fixed it by using `client.close()` instead of `db.close()`.

**Comment by seppevs** [comment]
README us updated. Closing this.
