### ISSUE TITLE
working with objectId

### ISSUE THREAD

**Issue by blackholegalaxy** [seppevs/migrate-mongo#119]
We used to use a simple nodeJS script using raw mongoDB for our migrations. Something like:
```
const MongoClient = require('mongodb').MongoClient;
const assert = require('assert');
const USERS= require('./models/entities').USERS;
const ObjectId = require('bson').ObjectId;
require('dotenv').config();

const client = new MongoClient(mongoDbConnectionString);
client.connect(async function(err) {
  assert.equal(null, err);
  console.log("Connected successfully to server");

  const db = client.db(MONGODB_DATABASE);

  for (const user of USERS) {
    const result = await db.collection(user).find({}, {_id: 1, credentialsId: 1 }).snapshot().toArray();

    for (entity of result) {
      const update = await db.collection('credentials').updateOne({ _id: ObjectId('123456789abc') }, { $set: { blacklisted: true } });
    }
  }

  client.close();
});
```

It works well with no problem. Due to our recent needs, we decided to use such a great migration tool like migrate-mongo with up and down flows.

Here is our script transcription:

```
const ObjectId = require('bson').ObjectId;
const USERS= require('../models/entities').USERS;

module.exports = {
  async up(db) {
    for (const user of USERS) {
      const result = await db.collection(user).find({}, {_id: 1, credentialsId: 1 }).snapshot().toArray();
  
      for (entity of result) {
        const update = await db.collection('credentials').updateOne({ _id: ObjectId('123456789abc') }, { $set: { blacklisted: true } });
        console.log(update.result);
      }
    }
  },

  down(db) { }
};
```

unfortunately this doesn't work. We don't have any error reported in console or thrown by migrate-mongo. But the database is not updated at all.

Could this come from objectId? We tried defining it with a simple string with no more successful results.

**Comment by TheBeege** [comment]
Did you ever solve this?

**Comment by misleadingTitle** [comment]
I've put `const ObjectId = require('mongodb').ObjectID` so I can do 

```
  async up(db,client) {
    
    db.collection('settingsMig').insertMany([
      {
        "_id": ObjectId("614d91eda5e14b489de90c89"
        }])
}
```

**Comment by theRocket** [comment]
This no longer works. I get the error:
```
> npx migrate-mongo up

ERROR: Could not migrate up 20230404223533-seed_accounts.js: Unsupported BSON version, bson types must be from bson 5.0 or later BSONVersionError: Unsupported BSON version, bson types must be from bson 5.0 or later
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3637:23)
    at serializeObject (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3199:22)
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3432:25)
    at serializeObject (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3199:22)
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3633:25)
    at Object.serialize (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:4015:32)
    at Msg.serializeBson (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:383:21)
    at Msg.makeDocumentSegment (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:377:37)
    at Msg.toBin (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:366:29)
    at MessageStream.writeCommand (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/message_stream.js:43:34)
```
