### ISSUE TITLE
Not following semantic versioning

### ISSUE THREAD

**Issue by jshbrntt** [seppevs/migrate-mongo#402]
[The change in question](https://github.com/seppevs/migrate-mongo/compare/v8.2.2...v8.2.3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L34) my automated migration hooks.

```
ERROR: options autoindex, usecreateindex, usefindandmodify are not supported MongoParseError: options autoindex, usecreateindex, usefindandmodify are not supported
    at Object.parseOptions (/srv/node_modules/migrate-mongo/node_modules/mongodb/lib/connection_string.js:291:15)
    at new MongoClient (/srv/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:62:46)
    at Function.connect (/srv/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:184:33)
    at Object.connect (/srv/node_modules/migrate-mongo/lib/env/database.js:16:38)
ERROR: All values of tls/ssl must be the same. MongoParseError: All values of tls/ssl must be the same.
    at Object.parseOptions (/srv/pinkie/node_modules/migrate-mongo/node_modules/mongodb/lib/connection_string.js:284:19)
    at new MongoClient (/srv/pinkie/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:62:46)
    at Function.connect (/srv/pinkie/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:184:33)
    at Object.connect (/srv/pinkie/node_modules/migrate-mongo/lib/env/database.js:16:38)
```

I wouldn't consider upgrading `mongodb` from `^3.6.4` to `^4.0.1` a patch version bump in `migrate-mongo`.

Please yank version `8.2.3` of the package and publish it again as `9.0.0`.

**Comment by seppevs** [comment]
Sorry, I'll follow the semver versioning with more care now. Closing this.
