### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by jrj2211** [seppevs/migrate-mongo#417]
**Describe the bug**
I am getting an error about using import in a project that uses ESM.

```
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require (/workspaces/mrp/node_modules/migrate-mongo/lib/utils/module-loader.js:3:12)
    at Object.loadMigration (/workspaces/mrp/node_modules/migrate-mongo/lib/env/migrationsDir.js:101:27) {
  migrated: []
}
```

I see line 101 in migrationsDir is doing a require thats surrounded by a try catch. Doesn't seem like e.code === ERR_REQUIRE_ESM as its not running that and rethrowing the error.

```
try {
      return moduleLoader.require(migrationPath);
    } catch (e) {
      if (e.code === 'ERR_REQUIRE_ESM') {
        return moduleLoader.import(url.pathToFileURL(migrationPath));
      }
      throw e;
    }
```

Since it seems like the moduleSystem config variable was recently added, how about using that instead of a try catch to run the appropriate loader?

```
const configContent = await config.read();
switch(configContent.moduleSystem) {
   case "esm":
      return moduleLoader.import(url.pathToFileURL(migrationPath));
      break;
   case "commonjs":
      return moduleLoader.require(migrationPath);
      break;
}
```

**To Reproduce**
I am using this via the programmable API.

```
migrate.config.set(this.config);
const { db, client } = await migrate.database.connect();
await migrate.up(db, client);
```

**Expected behavior**
Should properly import when in esm environment.

**Additional context**
I am running this as a bin script. Package.json is set to type module and my config file for migrate-mongo has moduleSystem: 'esm'.

**Comment by deiay** [comment]
I'm having the same issue

**Comment by lukjaki** [comment]
I'm experiencing similar issue.

**Comment by onurcskun** [comment]
I'm having the same issue as well.

**Comment by a-warner-knight** [comment]
I had the same issue when running from a quick and dirty docker image based on node-20, with migrate-mongo installed globally running the raw scripts, rather than from within a package. I worked around it by changing the migrate-mongo-config.js and migrations/* scripts to be non-esm.

In migrate-mongo-config.js:
- `module.exports = { ... }` instead of `const config = { ... }; export default config;`

In scripts:
- `module.exports.up = async...` instead of `export const up = async...`, similarly for down
- `const { ObjectId } = require('../path/to/mongodb/lib/index.js')` instead of `import { ObjectId } from 'mongodb'`
- `new ObjectId()` instead of just `ObjectId()`

Hope that helps someone looking for a quick fix.

**Comment by redmonkez12** [comment]
I used "migrationFileExtension": ".js" or switched in tsconfig.json to "target": "ES6"

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/95f2ca46-3a40-428f-97d8-4a5637192cc1" />
