### ISSUE TITLE
Assigning an `_id` field with a valid mongodb ObjectID value gives a BSON version error

### ISSUE THREAD

**Issue by theRocket** [seppevs/migrate-mongo#434]
**Describe the bug**
Cannot assign an `_id` field a mongodb ObjectID value. Receive BSON version error. Code below produces:
```
> npx migrate-mongo up

ERROR: Could not migrate up 20230404223533-seed_accounts.js: Unsupported BSON version, bson types must be from bson 5.0 or later BSONVersionError: Unsupported BSON version, bson types must be from bson 5.0 or later
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3637:23)
    at serializeObject (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3199:22)
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3432:25)
    at serializeObject (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3199:22)
    at serializeInto (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:3633:25)
    at Object.serialize (~/.npm/_npx/d044f46583e57438/node_modules/bson/lib/bson.cjs:4015:32)
    at Msg.serializeBson (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:383:21)
    at Msg.makeDocumentSegment (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:377:37)
    at Msg.toBin (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/commands.js:366:29)
    at MessageStream.writeCommand (~/.npm/_npx/d044f46583e57438/node_modules/mongodb/lib/cmap/message_stream.js:43:34)
```

**To Reproduce**
Using a valid ObjectID string value from MongoDB itself:
```
const ObjectId = require('mongodb').ObjectId
const _id = new ObjectId('6452aa310a837f409e96e2e8')

module.exports = {
  async up (db, client) {
    const session = client.startSession()
    try {
      await session.withTransaction(async () => {
        const newAccount = {
          _id,
          name: 'Test Data'
        }
        const result = await db.collection('accounts').insertOne(newAccount)
        console.log('Seeded account:', result)
      })
    } finally {
      await session.endSession()
    }
  },

  async down (db, client) {
    const session = client.startSession()
    try {
      await session.withTransaction(async () => {
        await db.collection('accounts').deleteOne({ _id })
      })
    } finally {
      await session.endSession()
    }
  }
}
```
Removing the `_id` field gives us: 
```
Seeded account: {
  acknowledged: true,
  insertedId: new ObjectId("6452ac3bb38f7175607d54d1")
}
MIGRATED UP: 20230404223533-seed_accounts.js
```

**Expected behavior**
Should be able to provide a valid BSON string value and assign the _id directly.

**Additional context**
It used to work based on https://github.com/seppevs/migrate-mongo/issues/119#issuecomment-930214631

**Comment by theRocket** [comment]
Even though our migrate-mongo command is this in `package.json`:
```
"migrate:up": "npx migrate-mongo up",
```
I had to bump the project dependencies like so:
```
  "dependencies": {
    ...
    "bson": "^5.2.0",
    ...
    "migrate-mongo": "^10.0.0",
    "mongodb": "^5.3.0",
    "mongoose": "^6.7.2"
  },
```
Then I could run the code above without errors.

**Comment by theRocket** [comment]
This issue has been addressed in Mongoose with Milestone 6.11.6:
https://github.com/Automattic/mongoose/issues/13712
and 7.4.0:
https://github.com/Automattic/mongoose/pull/13515

**Comment by seppevs** [comment]
So it's an issue with Mongoose, and not migrate-mongo?

**Comment by ItsBradyDavis** [comment]
Just confirming that this is still an issue. 

Fixed by updating bson in my dependencies.
