### ISSUE TITLE
Upgrade to v10.0.0 and cannot check migrate mongo version

### ISSUE THREAD

**Issue by coroo** [seppevs/migrate-mongo#435]
**Describe the bug**
I just update the v10.0.0 and got an error when checking version.

**To Reproduce**
1. Update to version 10.0.0
2.  run this script:
```
migrate-mongo --version
```
3. It will return the error:
```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'mongodb'
Require stack:
- /Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/lib/env/database.js
- /Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/lib/migrate-mongo.js
- /Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/bin/migrate-mongo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/lib/env/database.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/lib/env/database.js',
    '/Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/lib/migrate-mongo.js',
    '/Users/kuncorowicaksono/.nvm/versions/node/v14.17.6/lib/node_modules/migrate-mongo/bin/migrate-mongo.js'
  ]
}
```

**Expected behavior**
Return the version of migrate-mongo, e.g. 9.0.0

**Comment by Juuldamen** [comment]
Same error when I run `migrate-mongo up` with v10 globally installed in a Docker container with image `node:14-alpine`. The repository has `mongoose@5.12.12` installed which also requires `mongodb@3.6.8` which is defined in the package-lock.json file. I can see it locally in `node_modules/mongodb`.

**Comment by prashantswami** [comment]
> migrate-mongo --version

12.1.3


It works in latest version. Could you please updating to latest version?
